name: Build web
on:
  push:
    branches:
      - feature/github-build
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "5 4 2 * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      #- uses: actions/cache@v2
      #  with:
      #    path: ~/.cache/my
      - name: build image
        run: docker build .
      - name: build website
        run: ./dockerenv-github.sh ./pack.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: pack.zip

  test-bleeding-edge-java-and-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build image
        run: docker build . --target bleeding-edge
      - name: build website
        run: env DOCKER_TAG=bleeding-edge ./dockerenv-github.sh ./pack.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: site-for-verification
          path: pack.zip

  compare:
    needs: [build, test-bleeding-edge-java-and-npm]
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: site
          path: ./build

      - name: Download test-bleeding-edge-java-and-npm artifact
        uses: actions/download-artifact@v3
        with:
          name: site-for-verification
          path: ./verification

      - name: Extract build artifact
        run: mkdir build/unpacked && unzip -d build/unpacked build/pack.zip

      - name: Extract test-bleeding-edge-java-and-npm artifact
        run: mkdir verification/unpacked && unzip -d verification/unpacked verification/pack.zip

      - name: Find
        run: find

      - name: Compare artifacts
        run: diff --exclude="*.gz" -r build/unpacked verification/unpacked
